# Generated by Django 5.0.6 on 2024-06-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witter', '0003_swit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics/'),
        ),
    ]
