# Generated by Django 5.0.6 on 2024-06-11 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witter', '0004_profile_profile_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='swit',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='swit_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='swit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swits', to=settings.AUTH_USER_MODEL),
        ),
    ]
